version: '3.3'

services:
  django:
    build: ./core
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./core:/core
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    command: ["yarn", "start"]
    volumes:
      - ./frontend:/frontend
      - node-modules:/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules: