# Generated by Django 2.2.3 on 2019-07-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(default='Write the answer', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(default='Write your question', max_length=500),
        ),
        migrations.AlterField(
            model_name='tag',
            name='discription',
            field=models.CharField(default='This is description', max_length=500),
        ),
    ]
