# Generated by Django 2.2.3 on 2019-08-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190805_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='use_cnt',
        ),
    ]
